### ISSUE TITLE
Node failing to start the app

### ISSUE THREAD

**Issue by oferze** [DecentCMS/DecentCMS#1]
I followed the instructions on GitHub exactly, but when I ran `node server` I got this error:

```
module.js:338

    throw err;

          ^

Error: Cannot find module 'decent-core-dependency-injection'

    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\Dev\DecentCMS\repo\modules\core\multi-tenancy\lib\shell.js:14:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

Could you please advise...

**Comment by bleroy** [comment]
Congratulations on opening the first issue ;)

That probably indicates a missing dependency in that module. If you have run grunt install without errors, that shouldn't happen. Can you check what you have in /modules/core/di/node_modules? You should see async in there at least.

**Comment by oferze** [comment]
Yes, async is there. I also manually ran `grunt install` and even `grunt update` on that folder, all returned with success, but it still fails when I run `node server` on the main folder...

BTW wanted to write you an email but your email on GitHub (bleroy@microsoft.com) bounces :)

**Comment by bleroy** [comment]
LOL. Wow, I have no idea why I didn't notice that old email address was still there.

OK, so now next thing we should try is see what's under node_modules in modules/core/multi-tenancy. I'm pretty sure I know how it failed, but I still want to check. In the meantime, I'll push a fix.

This is one of the only places where I had to have one module depend on another in a hard way, and I failed at it :/

**Comment by bleroy** [comment]
You can also fix this by opening a command-line under /modules/core/multi-tenancy and doing npm install ../di, I think.

**Comment by bleroy** [comment]
I pushed what I think should fix it.

**Comment by oferze** [comment]
I managed to "fix" it by changing line 14 of `modules/core/multi-tenancy/lib/shell.js` to:
`var scope = require('../../di').scope;` but let me see your update...

**Comment by bleroy** [comment]
Yes, you don't want to do that, in fact, because you're moving the information about where the package is from package.json to the actual code.

**Comment by bleroy** [comment]
Can you tell me what version of npm you're using? npm --version

**Comment by oferze** [comment]
Your fix works! Obviously much better than mine, as you've explained... I just tried to hack a quick solution til you come up with a decent one. I'm still amateur in the Node packages world (future people who read it: hopefully by the time you read it I won't be such an amateur so don't take this comment too seriously)

**Comment by oferze** [comment]
I have the latest Node version for Windows: v0.12.0

**Comment by bleroy** [comment]
Cool, I was in fact asking about your npm version, as referencing a local module requires npm 2 or later.

**Comment by oferze** [comment]
Oops... sorry - it's 2.5.1

**Comment by bleroy** [comment]
Great, thanks. I also updated the readme to indicate that npm >2 is needed.

Can we close this now?

**Comment by oferze** [comment]
Sure :)
Good luck with this new CMS, I look forward to see further developments!

**Comment by bleroy** [comment]
Thanks!
