### ISSUE TITLE
Tests fail to run

### ISSUE THREAD

**Issue by stevetayloruk** [DecentCMS/DecentCMS#10]
1. grunt-mocha-test not found locally to di module
2. JSDoc File parser error:
   
   |   22 passing (91ms)
   |   1 failing
   | 
     1) JsDoc File Parser parses JavaScript files for JsDoc:
     TypeError: undefined is not a function
     at Object.parseJsDoc  (C:...\DecentCMS\modules\core\documentation\services\jsdoc-content-file-parser.js:108:32)
     at Context.<anonymous> (C:...\DecentCMS\modules\core\documentation\test\index.js:482:12)

**Comment by stevetayloruk** [comment]
It seems that there is a little confusion also around mocha.  Needs to be locally installed but not in package.json

**Comment by bleroy** [comment]
I'm not sure I understand what you mean. Do an `npm install` from the module's directory.

**Comment by stevetayloruk** [comment]
yes, but shouldn't this happen at the grunt level when it goes through each module and call npm install?  

The other issue is not a dependency issue though.

**Comment by bleroy** [comment]
Yes, it should. When you do `grunt install`, if should install all dependencies, including dev dependencies. `grunt install_runtime` does only runtime dependencies. I'll check.

The second issue looks like another missing dependency in the documentation module.

All this seems to point to a failed `grunt install`. I think this means we need to move to a centralized management of dependencies as soon as possible.

**Comment by bleroy** [comment]
You can now do `npm test` from any module or from the root. You can also use the mocha sidebar extension to run and debug tests in VS Code.
