### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by HansS** [DecentCMS/DecentCMS#2]
cannot find module 'decent-core-dependency-injection'

....at..........modules\core\multi-tenancy\lib\shell.js:14;13.....

**Comment by bleroy** [comment]
Hi, thanks for reporting this. It looks like an exact duplicate of issue #1. Can you do npm --version and check that you have version 2 or above?

**Comment by HansS** [comment]
Hi Bertrand,i have Npm Version 2.5.1 and Node 32bit version 0.12.0 on Windows 8.1 (no Visual Studio install)
kind regardsHans

Date: Thu, 26 Feb 2015 08:08:30 -0800

**Comment by bleroy** [comment]
And you did a `grunt install` that ran without errors?

**Comment by HansS** [comment]
I am not 100% sure, but i think the error occured after: grunt install!Hans


Date: Thu, 26 Feb 2015 21:05:05 -0800

**Comment by HansS** [comment]
Hi Bertrand,i run grunt install again. This time the installation went through with no errors:" Done, without errors"!
Hans

Date: Thu, 26 Feb 2015 21:05:05 -0800

**Comment by bleroy** [comment]
So is it working now?

**Comment by HansS** [comment]
Hi Bertrand,the error occurs after: "node server.js" ( see attached files)Hans

Date: Thu, 26 Feb 2015 21:28:14 -0800

**Comment by bleroy** [comment]
I don't see attached files. Can you check what directories you have under /modules/core/multi-tenancy/node_modules?

**Comment by HansS** [comment]
27.02.2015  06:12    <DIR>          .27.02.2015  06:12    <DIR>          ..27.02.2015  06:11    <DIR>          async27.02.2015  06:11    <DIR>          chai26.02.2015  06:41    <DIR>          grunt-mocha-test27.02.2015  06:11    <DIR>          proxyquire
Date: Thu, 26 Feb 2015 22:00:17 -0800

**Comment by bleroy** [comment]
Yes, for some reason the di dependency didn't install. Can you run a `npm install` from `/modules/core/multi-tenancy`?

Also, would it be possible to answer on Github rather than through email? It does weird things to your formatting. Thanks!

**Comment by HansS** [comment]
C:\Users\Hans\web\cms\DecentCMS\modules\core\multi-tenancy>npm install
npm WARN package.json decent-core-multi-tenancy@0.0.0 No repository field.
npm WARN package.json decent-core-multi-tenancy@0.0.0 No README data
decent-core-dependency-injection@0.0.0 node_modules\decent-core-dependency-injection

mocha@2.1.0 node_modules\mocha
├── escape-string-regexp@1.0.2
├── diff@1.0.8
├── growl@1.8.1
├── commander@2.3.0
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
└── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)

C:\Users\Hans\web\cms\DecentCMS\modules\core\multi-tenancy>

**Comment by bleroy** [comment]
Oh, so that worked? I think there's still an issue here, that I'll fix. Thanks for your patience.
