### ISSUE TITLE
Cool stuff...a suggestion....

### ISSUE THREAD

**Issue by GQAdonis** [DecentCMS/DecentCMS#6]
This looks to be a cool project, because as you know, I have always been a big fan of Orchard.  I really would like to see it implemented in Node.js, so I will help.

As for this code base, I think you know it does not run as is, and I have a suggestion to fix a piece of it.

To make modules easier to create by eliminating the need to resolve paths to precise directories, you can use the "require-alias" module, which allows for mapping generic names to exact paths.  You could, in "server.js", iterate over the modules directory creating "name/path" pairs.  In new modules, use the alias to bring in the functionality of the desired module.

I have created an example of this and submit a pull request for your review if you like the idea.

**Comment by bleroy** [comment]
Thanks. I've commented on the pull request. The current module resolution does solve the same problem, and you should almost never have to require by path, except in tests, but I think that's fine. There is an exception in multi-tenancy, but that will go away once I've extracted di as a npm package.
