### ISSUE TITLE
Architecture 

### ISSUE THREAD

**Issue by DBJDBJ** [DecentCMS/DecentCMS#9]
## Glad to see Architecture has at least it's own folder. 
Glad to see Architectural Principles are recorded and followed.  
I know that time is one rare commodity.  
I would like to join as an Architect. 
I would like to
* use ArchiMate
** use Wiki for describing and cooperating on Arch.
** use web site for the presenting Arch
* align the implementation with Architecture
* manage requirements
* Use Arch to streamline the onboarding

**Comment by bleroy** [comment]
Can we start discussing on the forums, and see where that leads us, and if it's insufficient? https://groups.google.com/forum/#!categories/decentcms/architecture
